### ISSUE TITLE
Remover prints do carregamento de bibliotecas

### ISSUE THREAD

**Issue by tarcisobraz** [analytics-ufcg/versoes-de-proposicoes#3]
Quando o fetcher.R é executado, a função require é executada para carregar as bibliotecas e imprime várias linhas que não fazem muito sentido e atrapalham o entendimento do usuário. Seria bom removê-las. As linhas impressas estão abaixo: 
[1] "Loading packages.."
[[1]]
[1] TRUE

[[2]]
[1] TRUE

[[3]]
[1] TRUE

[[4]]
[1] TRUE

[[5]]
[1] TRUE

[[6]]
[1] TRUE

[[7]]
[1] TRUE

[[8]]
[1] TRUE

[[9]]
[1] TRUE

[[10]]
[1] TRUE

[[11]]
[1] TRUE

[[12]]
[1] TRUE

[[13]]
[1] TRUE

[[14]]
[1] TRUE

**Comment by hadrizia** [comment]
A mensagem de carregamento das bibliotecas agora está a seguinte:

 ```
RCurl     dplyr    lubridate     magrittr        stats      stringr       tibble        tidyr        utils     devtools  
TRUE      TRUE    TRUE         TRUE          TRUE    TRUE       TRUE       TRUE     TRUE  TRUE 
    optparse   here     rcongresso   agoradigital 
    TRUE       TRUE   TRUE           TRUE 
```
